name = "Crownfall"
author = "ADMINSCROWNFALL"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "cc790a32021a66134ad0c28fb4b8e3482f2751b301642ca18df399ab7e6b369a"

[versions]
forge = "47.4.0"
minecraft = "1.20.1"
