name = "Crownfall"
author = "ADMINSCROWNFALL"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "f11a95423e3d3d648ed4c2e3d60006d8bbebd89a7ed6c7eb03fe56594559d8b9"

[versions]
forge = "47.4.0"
minecraft = "1.20.1"
