name = "Crownfall"
author = "ADMINSCROWNFALL"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "13549b7940c19f3889f8e7bf7c6c9de7e8ec5601cd7fbedbc97eff568185ea77"

[versions]
forge = "47.4.0"
minecraft = "1.20.1"
